### ISSUE TITLE
strange tearing when loading bathymetric shape with loadShape

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#37]
Getting some artifacts in the bathymetry layer when loading a shape with loadShape and a buffer:

```R
library(raster)
shape = loadShape(path='../data/STX_Land_Shapefile/', 
                  shape='Extracted_Land.shp', 
                  size=10, buffer=10)

shape.latlon = projectRaster(shape, crs=crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))

plotRaster(input = actel_out, base.raster=shape.latlon, 
           coord.x="Longitude", coord.y="Latitude", size=1) 
```
gives: 

![Screen Shot 2020-06-22 at 5 21 18 PM](https://user-images.githubusercontent.com/3063276/85732764-0581c700-b6d2-11ea-82ed-e7afe9291404.png)

which seems to contain some grid-like artifacts. this may be a problem in the projectRaster step, but I wanted to put it up here for future reference and to see if we have any idea what's causing the tearing?

**Comment by hugomflavio** [comment]
Hi Jon!

I have come across that weird effect before too. If I remember correctly, it happened when the raster was in WGS84 and we tried converting it to UTM using the projectRaster function (to plot the overlaps in RSP). I don't know why that happens, but I have found that the projectRaster function is a bit moody. For example:

```r
# imagine these are two rasters
a # raster in wgs84
b # raster in UTMx

# there are two ways to get 'b' into the same coord system as 'a'

# by doing this:
output1 <- raster::projectRaster(b, crs = raster::crs(a))

# or by doing this
output2 <- raster::projectRaster(b, to = a)

# But these do not yield the same result, even though in theory the information 
# passed should be the same (as far as I understand it).
output1 != output2
```

To avoid this, in RSP we ended up converting the dynBBMM output back to WGS84 (rather than converting the base raster to UTM) when plotting areas/contours/overlaps (which also only actually worked using the second method I mentioned above).

I also seem to remember that this is not a ggplot artifact, as using `raster::plot()` also returned that background noise.

My recommendation would be to import the shapefile into R already in the coordinate system you intend to use throughout the analysis.

This is more of an RSP problem than an actel problem though; 'plotRaster()' belongs to RSP (although I think I will eventually code something similar for actel, using the spatial data frame as an argument to supply the stations).

Let me know if that helped :)

**Comment by hugomflavio** [comment]
Closing this one for now as it does not appear to be directly linked to actel
