### ISSUE TITLE
Issue with release sites re: Residency

### ISSUE THREAD

**Issue by jessicas09** [hugomflavio/actel#83]
I'm receiving the following error and I'm not sure why. I've already confirmed that the release sites are spelled exactly the same (including no extra spaces) on both files. Has anyone else had this issue?

> Error: The following release sites were listed in the biometrics.csv file but are not part of the release sites listed in the spatial.csv file: WB12, WB6, WB7, WB8

<img width="471" alt="spatial" src="https://user-images.githubusercontent.com/119961401/205975530-b0b2329b-c14e-4620-ba18-b94b7e95a3b0.png">
<img width="621" alt="biometrics" src="https://user-images.githubusercontent.com/119961401/205975545-26933545-dc58-4c6c-aa78-8fbe7bba2015.png">

**Comment by hugomflavio** [comment]
Hi Jessica!

Thanks for trying out actel. 

I can see from your spatial.csv file that you have listed WB6, 7, ..., 13 as "Hydrophone" stations, rather than "Release" stations. Is that intentional? I.e. do you have hydrophones at those locations? If, for example, WB6 is both the location of an hydrophone and also a location where fish were released, then you should create two stations (one for the hydrophone and another for the release).

e.g.:

|Station.name | Latitude | Longitude | Section | Array | Type                |
|-------------------- | ------------ | --------------- | ---------- | --------| -------------------- |
|WB6                 | ...             | ...                | Bay        | WB6   | Hydrophone |
|WB6-R             | ...             | ...                |                | WB6   | Release          |

Then use "WB6-R" as the release site for your fish.

Hope that helps!

**Comment by jessicas09** [comment]
Yes, WB6, 7, ..., 13 are all hydrophones. And the other ones (WB210915-03...WB220926-13) are individual fish IDs. I have the "Release" arrays as the location where the fish would first be expected to cross (aka the closest hydrophone when released). So I think that's the same as your example, right? Except I'm using the fish ID as the release site name. Does that not make sense?

**Comment by jessicas09** [comment]
AH! I thought that the "release site" on the biometrics needed to match one of the "hydrophone" Station.name's on the spatial, in order to indicate which hydrophone the animal would first appear on.

This worked! Thanks for your (quick!!) response and explanation!! You rock!
